### ISSUE TITLE
docker compose up --build fails with uv replacement

### ISSUE THREAD

**Issue by bkimjin** [cnstlungu/portable-data-stack-dagster#14]
<img width="1170" alt="image" src="https://github.com/user-attachments/assets/b2f41cd6-1e79-4cd5-8650-08b7cb30d493">

When reverting https://github.com/cnstlungu/portable-data-stack-dagster/commit/5deead7e9dde26c4024c68757ce1a05be0e6cbc1, docker compose works as expected.

**Comment by cnstlungu** [comment]
Hello @bkimjin, thanks a lot for pointing it out!

Sorry for that. Should be all good now.

<img width="1371" alt="image" src="https://github.com/user-attachments/assets/90e2b803-bc54-4e82-9a52-e6ec1b3ae390">
